#+STARTUP: showall

#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800 reveal_slide_number:c/t
#+OPTIONS: toc:0
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: cube
#+REVEAL_THEME: moon
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Человечная декомпозиция работы">
#+REVEAL_POSTAMBLE: <p> Created by Alexander Petrov (a.k.a Lysenko). </p>
#+REVEAL_PLUGINS: (markdown notes)
#+REVEAL_EXTRA_CSS: ./local.css

* Человечная декомпозиция работы

#+ATTR_REVEAL: :frag roll-in
Сокращёно *ЧеДеР*

#+ATTR_REVEAL: :frag roll-in
*ИЛИ*

#+ATTR_REVEAL: :frag roll-in
*Декомпозирование личностями для личностей*

#+ATTR_REVEAL: :frag roll-in
Сокращённо *ДеЛиДяЛи*

#+ATTR_REVEAL: :frag roll-in
По английски *Person Concerned Work Decomposition (PСWD)*

* About me

#+ATTR_REVEAL: :frag roll-in
*Alexander Petrov* (a.k.a Lysenko)

#+ATTR_REVEAL: :frag roll-in
*Pragmatic Programmer* | *Sing, Play Sax & Guitar* | *#Clojure, #Emacs*

#+ATTR_REVEAL: :frag roll-in
Старший разработчик *Clojure* Центра продуктов Дозор в Ростелеком Солар

#+ATTR_REVEAL: :frag roll-in
*2015 - 2022*
Старший *Ruby* / *Rails* / *Erlang* Разработчик в FunBox

#+ATTR_REVEAL: :frag roll-in
*2006 - 2014* Enterprise *Java* Developer / Trainer / Architect / Team Leader

* Состояние потока

#+ATTR_REVEAL: :frag roll-in
Механизмы работы мозга

#+ATTR_REVEAL: :frag roll-in
/Быстрый, автоматический/ - незатратный, может подводить

#+ATTR_REVEAL: :frag roll-in
/Медленный, аналитический/ - высокозатратный, позволяет получать более взвешенные решения

#+ATTR_REVEAL: :frag roll-in
Исключение - состояние *потока*

#+ATTR_REVEAL: :frag roll-in
Результативность и концептуальная целостность (качество) результата в состоянии *потока* недостижимы без этого состояния

#+ATTR_REVEAL: :frag roll-in
В состоянии *потока* открывается доступ к *смётке*

* Смётка

#+ATTR_REVEAL: :frag roll-in
*Смётка* - (в специальном смысле) способность ментально пердставлять функционирование конкретного или абстрактного механизма и находить решения для его исправления или усовершенствования

#+ATTR_REVEAL: :frag roll-in
Что истощает  *смётку*?

#+ATTR_REVEAL: :frag roll-in
Переключение контекста, суета, отсутствие автоматизации и навыков

#+ATTR_REVEAL: :frag roll-in
Что восстанавливает?

#+ATTR_REVEAL: :frag roll-in
Интерес, созерцание и уединение

#+ATTR_REVEAL: :frag roll-in
*#HammockMode* *#Рыбалка* *#Физкультура* *#ЗанятияМузыкой*

* Неконструктивные убеждения о людях 1/2

#+ATTR_REVEAL: :frag roll-in
Следующие 6 убеждений о человеческой природе не конструктивно класть в основу управления креативной деятельностью, в особенности созданием ПО

#+ATTR_REVEAL: :frag roll-in
- Человек от природы порочен, и только давление общества заставляет его сдерживать свои порывы.

#+ATTR_REVEAL: :frag roll-in
- Человек ленив, и его нужно заставлять работать, иначе он будет прокрастинировать.

#+ATTR_REVEAL: :frag roll-in
- Человек склонен до бесконечности улучшать любой достаточно хороший результат, даже если это не несёт никакой ценности заинтересованным лицам (перфекционизм).

* Неконструктивные убеждения о людях 2/2

#+ATTR_REVEAL: :frag roll-in
- Человеком движет жажда материальных ценностей для себя (эгоизм и алчность).

#+ATTR_REVEAL: :frag roll-in
- Человек нуждается в подчинении и в том, чтобы ему подчинялись (авторитаризм).

#+ATTR_REVEAL: :frag roll-in
- Человек не любит людей и стремится избегать взаимодействия с ними в процессе решения рабочих и жизненных задач (мизантропия).

* Закон Паркинсона

#+ATTR_REVEAL: :frag roll-in
Работа заполняет время, отпущенное на неё

#+ATTR_REVEAL: :frag roll-in
*1955* - Сирил Норткот Паркинсон. Сатиристическая статья о бюрократии.

#+ATTR_REVEAL: :frag roll-in
Менеджмент индустрии ПО ошибочно взял на вооружение этот неуместный для креативной деятельности /"закон"/.

* #микротаскинг

#+ATTR_REVEAL: :frag roll-in
Веря в "закон" Паркинсона можно дойти до решения "проблем" с человеческой природой через #микротаскинг

#+ATTR_REVEAL: :frag roll-in
Бесчеловечный подход, характерный для работы крупных капиталистических производств

#+ATTR_REVEAL: :frag roll-in
- Подразумевается, что людям нужно платить за сделанную мелкую работу, которую они могут сделать не задумываясь о целостности и полезности результата

#+ATTR_REVEAL: :frag roll-in
- О /целостности/ заботятся "Архитекторы" (*авторитеты*), которые знают, как все фичи поделить на атомы, чтобы обезличенные /люди-роботы/ их выполняли

* #NoEstimates

#+ATTR_REVEAL: :frag roll-in
Если понимать ценность *потока* и *сметки* то можно каждую фичу делать целиком, не давая никаких оценок.

#+ATTR_REVEAL: :frag roll-in
Предварительные оценки не нужны! Работа будет сделана тогда, когда будет достигнуто концептуально целостное решение. А случится это всё равно это быстрее, чем мы закончим оценивать.

* #NoEstimates может не сработать

#+ATTR_REVEAL: :frag roll-in
*No Estimates* может не сработать, если хотя бы один пункт выполняется (расположены в порядке влияния и распространённости):

#+ATTR_REVEAL: :frag roll-in
- используются /мейнстримовые/ технологии с /посредственной/ продуктивностью из-за *accidental complexity*

#+ATTR_REVEAL: :frag roll-in
- команды не состоят из /"10X"/ программистов

#+ATTR_REVEAL: :frag roll-in
- стейкхолдеры нуждаются в ориентировочных сроках (*B2B*, *B2C*, *Digital* с нуждой в /маркетинге/ и /рекламе/)

#+ATTR_REVEAL: :frag roll-in
- кодовая база велика, *inherent complexity* высока и любое изменение требует больших затрат времени
  
* Декомпозиция работы ради проектирования

#+ATTR_REVEAL: :frag roll-in
Кто нам "мешает", тот нам поможет!

#+ATTR_REVEAL: :frag roll-in
Даже если мы могли бы следовать идее #NoEstimates, декомпозировать работу полезно для фокусировки мыслительного процесса

